name: sis
description: "SIS — Stay In Sync."
publish_to: 'none'
version: 0.1.0-dev.2+2

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  google_sign_in: ^7.2.0
  supabase_flutter: ^2.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
